[package]
name = "ferrisync"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
ferrisync-core = { path = "../ferrisync-core" }
tokio.workspace = true
anyhow.workspace = true
clap.workspace = true
env_logger.workspace = true
log.workspace = true
ratatui.workspace = true
crossterm.workspace = true
dirs.workspace = true
blake3.workspace = true
chrono.workspace = true
uuid.workspace = true
whoami.workspace = true
rustyline.workspace = true
shlex.workspace = true

[dev-dependencies]
tempfile = "3"